path_classifiers:
  library:
    - exclude: /
extraction:
  cpp:
    index:
      build_command:
        - export 'CFLAGS=-Iinclude -ansi -Wall -Wextra -Wpedantic -Werror'
        - make -C source core_json.o
